# Numpy


In [2]:
import numpy as np

In [ ]:
array_1 = np.array([9, 10, 11, 12])
print(array_1)
print(type(array_1))

[ 9 10 11 12]
<class 'numpy.ndarray'>


In [ ]:
array_2 = np.array((9, 10, 11, 12))
print(array_2)
print(type(array_2))

[ 9 10 11 12]
<class 'numpy.ndarray'>


In [ ]:
list_1 = [1, 2, 3, 4]
list_2 = [2, 4, 6, 8]
print(list_1 + list_2)

[1, 2, 3, 4, 2, 4, 6, 8]


In [ ]:
list_1 = np.array([1, 2, 3, 4])
list_2 = np.array([2, 4, 6, 8])
print(list_1 + list_2)

[ 3  6  9 12]


In [7]:
print(list_1-list_2)
print(list_1*list_2)
print(list_1/list_2)

[-1 -2 -3 -4]
[ 2  8 18 32]
[0.5 0.5 0.5 0.5]


In [ ]:
def calculate_dot_product(a, b):
    if len(a) == len(b):

        return sum(a * b)


print(calculate_dot_product(np.array([1, 2, 3, 4]), np.array([2, 4, 6, 8])))

60


Multidiementional array


In [ ]:
array_2 = np.array([
    [6, 8, 4, 7, 5],
    [9, 4, 3, 6, 8],
    [10, 3, 9, 4, 6]
])

print(array_2)

[[ 6  8  4  7  5]
 [ 9  4  3  6  8]
 [10  3  9  4  6]]


In [18]:
print(array_2.shape)

(3, 5)


In [19]:
print(array_2.ndim)

2


In [20]:
print(array_2.size)

15


In [21]:
print(len(array_2))

3


In [ ]:
array_3 = np.array([
    [
        [1, 2],
        [3, 4],
        [5, 6]
    ], [
        [7, 8],
        [9, 6],
        [3, 7]
    ],
    [
        [8, 12],
        [36, 47],
        [3, 74]
    ]
])

print(array_3)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9  6]
  [ 3  7]]

 [[ 8 12]
  [36 47]
  [ 3 74]]]


In [23]:
print(array_3.shape)
print(array_3.ndim)
print(array_3.size)
print(len(array_3))

(3, 3, 2)
3
18
3


In [ ]:
array_1 = np.array([10, 20, 30, 50], dtype=np.int8)
print(array_1.dtype)

int8


: 

In [3]:
array_2 = np.array([1.2, 2.8, 3.6])
print(array_2.dtype)

float64


In [ ]:
array_1 = np.array([
    [1, 9, 5, 8],
    [4, 5, 3, 6],
    [6, 5, 4, 10]
])

print(array_1[1])  # array_1[1,:]
print("----------------")
print(array_1[0:3, 2])

print("----------------")
print(array_1[1:])
print("----------------")
print(array_1[0:2, 1::])

[4 5 3 6]
----------------
[5 3 4]
----------------
[[ 4  5  3  6]
 [ 6  5  4 10]]
----------------
[[9 5 8]
 [5 3 6]]


Scalar multiplication


In [ ]:
array_1 = np.array([
    [1, 9, 5, 8],
    [4, 5, 3, 6],
    [6, 5, 4, 10]
])

print(2*array_1)

[[ 2 18 10 16]
 [ 8 10  6 12]
 [12 10  8 20]]


In [ ]:
c = np.array([
    [1, 2],
    [3, 4]
])

d = np.array([
    [5, 6],
    [7, 8]
])

print(c*d)

[[ 5 12]
 [21 32]]


In [ ]:
a = np.array([
    [1, -2, -6],
    [3, 4, -3],
    [3, 1, 2]
])

b = np.array([
    [1, 4, 3],
    [0, -2, 3],
    [6, 1, 0]
])

print(a@b)
print("--------------------------------------------------")
print(b@a)
print("--------------------------------------------------")

print(np.matmul(a, b))
print("--------------------------------------------------")
print(np.dot(a, b))

[[-35   2  -3]
 [-15   1  21]
 [ 15  12  12]]
--------------------------------------------------
[[ 22  17 -12]
 [  3  -5  12]
 [  9  -8 -39]]
--------------------------------------------------
[[-35   2  -3]
 [-15   1  21]
 [ 15  12  12]]
--------------------------------------------------
[[-35   2  -3]
 [-15   1  21]
 [ 15  12  12]]


In [ ]:
A = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [7, 8, 9, 10]
])


print(A.shape)
print("-"*10)
print(A.T)
print("-"*10)
print(A.T.shape)

(3, 4)
----------
[[ 1  5  7]
 [ 2  6  8]
 [ 3  7  9]
 [ 4  8 10]]
----------
(4, 3)
