In [2]:
import numpy as np

In [ ]:
list_a = [1, 2, 3]
list_b = [4, 5, 6]
print(list_a+list_b)

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a+b)

[1, 2, 3, 4, 5, 6]
[5 7 9]


In [4]:
print(a-b)
print(a*b)
print(a/b)

[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [ ]:
def calculate_dot_product(v1, v2):
    if len(v1) == len(v2):
        return sum(v1*v2)


print(calculate_dot_product(np.array([2, 4, 6]), np.array([3, 5, 7])))

68


In [ ]:
array_1 = np.array([
    [1, 2, 3, 4, 5],
    [2, 4, 5, 6, 7],
    [3, 5, 7, 8, 9]
])

print(array_1)

[[1 2 3 4 5]
 [2 4 5 6 7]
 [3 5 7 8 9]]


In [13]:
print(array_1.shape)

(3, 5)


In [14]:
print(array_1.dtype)

int64


In [15]:
print(array_1.ndim)

2


In [16]:
print(len(array_1))

3


In [17]:
print(array_1.size)

15


In [18]:
array_2 = np.array([
    [
        [1, 2],
        [3, 4],
        [5, 6]
    ],
    [
        [1, 2],
        [3, 4],
        [5, 6]
    ],
    [
        [1, 2],
        [3, 4],
        [5, 6]
    ]
])

print(array_2)

[[[1 2]
  [3 4]
  [5 6]]

 [[1 2]
  [3 4]
  [5 6]]

 [[1 2]
  [3 4]
  [5 6]]]


In [22]:
print(array_2.shape)
print(array_2.ndim)
print(array_2.size)
print(len(array_2))

(3, 3, 2)
3
18
3


In [ ]:
array_3 = np.array([10, 20, 30, 40, 50], dtype=np.int16)
print(array_3.dtype)

int16


In [ ]:
array_4 = np.array([10.5, 20.5, 30.5, 40.5, 50.5], dtype=np.float32)
print(array_4.dtype)

float32


In [33]:
matrix_1 = np.array([
    [1, 9, 5, 8],
    [4, 5, 3, 6],
    [6, 5, 4, 10]
])

print(matrix_1[1])
print("-"*20)
print(matrix_1[:,2])
print("-"*20)
print(matrix_1[1:])
print("-"*20)
print(matrix_1[:2,1:])

[4 5 3 6]
--------------------
[5 3 4]
--------------------
[[ 4  5  3  6]
 [ 6  5  4 10]]
--------------------
[[9 5 8]
 [5 3 6]]
