In [2]:
import numpy as np

In [3]:
list_a = [1, 2, 3]
list_b = [4, 5, 6]
print(list_a+list_b)

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a+b)

[1, 2, 3, 4, 5, 6]
[5 7 9]


In [4]:
print(a-b)
print(a*b)
print(a/b)

[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [5]:
def calculate_dot_product(v1, v2):
    if len(v1) == len(v2):
        return sum(v1*v2)


print(calculate_dot_product(np.array([2, 4, 6]), np.array([3, 5, 7])))

68


In [6]:
array_1 = np.array([
    [1, 2, 3, 4, 5],
    [2, 4, 5, 6, 7],
    [3, 5, 7, 8, 9]
])

print(array_1)

[[1 2 3 4 5]
 [2 4 5 6 7]
 [3 5 7 8 9]]


In [7]:
print(array_1.shape)

(3, 5)


In [8]:
print(array_1.dtype)

int64


In [9]:
print(array_1.ndim)

2


In [10]:
print(len(array_1))

3


In [11]:
print(array_1.size)

15


In [12]:
array_2 = np.array([
    [
        [1, 2],
        [3, 4],
        [5, 6]
    ],
    [
        [1, 2],
        [3, 4],
        [5, 6]
    ],
    [
        [1, 2],
        [3, 4],
        [5, 6]
    ]
])

print(array_2)

[[[1 2]
  [3 4]
  [5 6]]

 [[1 2]
  [3 4]
  [5 6]]

 [[1 2]
  [3 4]
  [5 6]]]


In [13]:
print(array_2.shape)
print(array_2.ndim)
print(array_2.size)
print(len(array_2))

(3, 3, 2)
3
18
3


In [14]:
array_3 = np.array([10, 20, 30, 40, 50], dtype=np.int16)
print(array_3.dtype)

int16


In [15]:
array_4 = np.array([10.5, 20.5, 30.5, 40.5, 50.5], dtype=np.float32)
print(array_4.dtype)

float32


In [ ]:
matrix_1 = np.array([
    [1, 9, 5, 8],
    [4, 5, 3, 6],
    [6, 5, 4, 10]
])

print(matrix_1[1])
print("-"*20)
print(matrix_1[:, 2])
print("-"*20)
print(matrix_1[1:])
print("-"*20)
print(matrix_1[:2, 1:])

[4 5 3 6]
--------------------
[5 3 4]
--------------------
[[ 4  5  3  6]
 [ 6  5  4 10]]
--------------------
[[9 5 8]
 [5 3 6]]


In [ ]:
matrix_2 = np.array([
    [1, 2, 3, 4],
    [4, 5, 6, 7],
    [6, 5, 7, 8]
])

print(2*matrix_2)

[[ 2  4  6  8]
 [ 8 10 12 14]
 [12 10 14 16]]


In [ ]:
matrix_3 = np.array([
    [2, 4],
    [6, 8]
])

matrix_4 = np.array([
    [1, 2],
    [3, 4]
])

print(matrix_3*matrix_4)

[[ 2  8]
 [18 32]]


In [19]:
a = np.array([
    [1, -2, -6],
    [3, 4, -3],
    [3, 1, 2]
])

b = np.array([
    [1, 4, 3],
    [0, -2, 3],
    [6, 1, 0]
])

print(a@b)
print("--------------------------------------------------")
print(b@a)
print("--------------------------------------------------")

print(np.matmul(a, b))
print("--------------------------------------------------")
print(np.dot(a, b))

[[-35   2  -3]
 [-15   1  21]
 [ 15  12  12]]
--------------------------------------------------
[[ 22  17 -12]
 [  3  -5  12]
 [  9  -8 -39]]
--------------------------------------------------
[[-35   2  -3]
 [-15   1  21]
 [ 15  12  12]]
--------------------------------------------------
[[-35   2  -3]
 [-15   1  21]
 [ 15  12  12]]


In [ ]:
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print(a)
print("-"*20)
print(a.T)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
--------------------
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


Indexing & Slicing


In [ ]:
M = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(M[0, 0])
print(M[1])
print(M[:, 0])
print(M[0:2, 1:3])

10
[40 50 60]
[10 40 70]
[[20 30]
 [50 60]]


Boolean masking


In [ ]:
scores = np.array([0.2, 0.9, 0.5, 0.95, 0.1])

mask = scores >= 0.5
print(mask)
print(scores[mask])

print(scores[scores >= 0.5])

[False  True  True  True False]
[0.9  0.5  0.95]
[0.9  0.5  0.95]


In [ ]:
X = np.array([
    [1, 2, 0.7],
    [3, 4, 0.9],
    [5, 6, 0.3]
])

print(X[X[:, 2] > 0.8])

[[3.  4.  0.9]]


In [ ]:
base = np.array([1, 2, 3, 4])
view = base[0:2]
view[0] = 99
print(base)

base2 = np.array([1, 2, 3, 4])
safe = base2[0:2].copy()
safe[0] = 99
print(base2)

[99  2  3  4]
[1 2 3 4]


Broadcasting


In [ ]:
X = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

column_mean = X.mean(axis=0)
print(column_mean)

centered = X - column_mean
print(centered)

[2.5 3.5 4.5]
[[-1.5 -1.5 -1.5]
 [ 1.5  1.5  1.5]]


In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(A.sum())
print(A.mean())
print(A.max())
print(A.min())

21
3.5
6
1


In [ ]:
print(A.sum(axis=0))
print(A.sum(axis=1))

[5 7 9]
[ 6 15]


Reshaping & Flattening


In [ ]:
r = np.arange(6)

print(r.reshape(2, 3))

print(r.reshape(3, 2))

[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]


In [ ]:
print(r.reshape(-1, 2))

[[0 1]
 [2 3]
 [4 5]]


In [ ]:
print(r.reshape(-1, 3))

[[0 1 2]
 [3 4 5]]


In [ ]:
grid = r.reshape(2, 3)
print(grid.flatten())

[0 1 2 3 4 5]


In [ ]:
u = np.array([1, 2, 3])
w = np.array([4, 5, 6])

print(np.vstack([u, w]))
print(np.hstack([u, w]))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [ ]:
c1 = np.array([[1], [2]])
c2 = np.array([[3], [4]])

print(np.concatenate([c1, c2], axis=1))

[[1 3]
 [2 4]]


Slicing train/test style splits


In [38]:
data = np.arange(10)

train = data[:8]
test = data[8:]

print(train)
print(test)

[0 1 2 3 4 5 6 7]
[8 9]


Shape debugging


In [40]:
X = np.array([
    [0.8, 0.4, 0.9],
    [0.2, 0.7, 0.6]
])

w = np.array([0.5, -0.2, 0.3])

print("X shape:", X.shape)
print('w shape:', w.shape)


print(X @ w)
print((X @ w).shape)

X shape: (2, 3)
w shape: (3,)
[0.59 0.14]
(2,)


Practical Lab


In [49]:
# Raw data: 4 samples, 3 features
X = np.array([
    [25, 50000, 0.9],
    [40, 60000, 0.3],
    [30, 52000, 0.8],
    [50, 58000, 0.6]
])

print('shape:', X.shape)
print(X.dtype)

# Keep only rows where the last feature(confidence) is >= 0.5
X = X[X[:, 2] >= 0.5]
print('after filtering: ', X)

# Scale each feature to a similar range using column min and  max
col_min = X.min(axis=0)
col_max = X.max(axis=0)
print(col_min, col_max)
X_scaled = (X-col_min)/(col_max-col_min)
print(X_scaled)

# Produce a score per sample with a weight vector and bias
w = np.array([0.3, 0.5, 0.2])
b = 0.05
score = X_scaled @ w + b
print('scores:', scores)

shape: (4, 3)
float64
after filtering:  [[2.5e+01 5.0e+04 9.0e-01]
 [3.0e+01 5.2e+04 8.0e-01]
 [5.0e+01 5.8e+04 6.0e-01]]
[2.5e+01 5.0e+04 6.0e-01] [5.0e+01 5.8e+04 9.0e-01]
[[0.         0.         1.        ]
 [0.2        0.25       0.66666667]
 [1.         1.         0.        ]]
scores: [0.2  0.9  0.5  0.95 0.1 ]


In [60]:
# Create
a = np.array([1, 2, 3])
z = np.zeros((2, 3))
o = np.ones((2, 2))
r = np.arange(0, 10, 2)
l = np.linspace(0, 1, 5)

# Inspect
a.shape
a.ndim
a.size
a.dtype

# Index / slice / mask
M = np.array([[10, 20, 30], [40, 50, 60]])
M[0, 1]
M[:, 0]
M[M > 25]

# Vectorized math & broadcasting
a*2
M - M.mean(axis=0)

# Aggregations
M.sum(axis=0)
M.sum(axis=1)


# Linear algebra
np.dot(a, a)
M @ M.T

# Reshape / Stack
np.arange(6).reshape(2, 3)
np.vstack([a, a])
np.hstack([a, a])

# Copy when need
safe = M[0:1].copy()