In [1]:
import numpy as np

arange(x,y,z)


In [2]:
arr = np.arange(0, 10, 2)
print(arr)

[0 2 4 6 8]


In [3]:
arr_1 = np.arange(0, 1, 0.1)
print(arr_1)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


linspace(x,y,z)


In [4]:
arr_2 = np.linspace(5, 17, 9)
print(arr_2)

[ 5.   6.5  8.   9.5 11.  12.5 14.  15.5 17. ]


zeros((x,y))


In [5]:
arr_3 = np.zeros((2, 3))
print(arr_3)

[[0. 0. 0.]
 [0. 0. 0.]]


ones((x,y))


In [6]:
arr_4 = np.ones((2, 3), dtype='int64')
print(arr_4)

[[1 1 1]
 [1 1 1]]


Boolean Masking


In [7]:
scores = np.array([0.6, 0.9, 0.3, 0.2, 0.75, 0.1])

temp_arr = scores > 0.5
print(temp_arr)

filtered_arr = scores[temp_arr]
print(filtered_arr)

[ True  True False False  True False]
[0.6  0.9  0.75]


In [8]:
print(scores[scores > 0.5])

[0.6  0.9  0.75]


In [9]:
scores = np.array([
    [3, 6, 4, 0.4],
    [1, 5, 8, 0.6],
    [2, 9, 12, 0.8],
    [4, 3, 7, 0.3]
])

print(scores[scores[:, -1] > 0.5])

[[ 1.   5.   8.   0.6]
 [ 2.   9.  12.   0.8]]


Copy vs View


In [10]:
base = np.array([6, 8, 5, 3, 4])
view = base[:3]
print(base)
print(view)

view[0] = 100
print(view)
print(base)

[6 8 5 3 4]
[6 8 5]
[100   8   5]
[100   8   5   3   4]


In [11]:
base = np.array([6, 8, 5, 3, 4])
view = base[:3].copy()
print(base)
print(view)

view[0] = 100
print(view)
print(base)

[6 8 5 3 4]
[6 8 5]
[100   8   5]
[6 8 5 3 4]


Broadcasting


In [12]:
A = np.array([
    [3, 5],
    [8, 9]
])

B = np.array([3, 2])

print(A+B)
print(B.shape)
print(A.shape)

[[ 6  7]
 [11 11]]
(2,)
(2, 2)


In [13]:
A = np.array([
    [3, 5],
    [8, 9],
    [10, 12]
])

B = np.array([
    [3],
    [2],
    [1]
])

# C = np.array([3,2,1])

print(A+B)
# print(A+C)

[[ 6  8]
 [10 11]
 [11 13]]


In [14]:
arr_2 = np.array([
    [1, 2, 3, 4],
    [2, 3, 4, 5],
    [1, 2, 3, 5],
    [2, 3, 4, 5]
])

arr_3 = np.array([
    [1, 2],
    [2, 3],
    [3, 4],
    [4, 5]
])

print(arr_2+arr_3)

ValueError: operands could not be broadcast together with shapes (4,4) (4,2) 

Aggregation function


In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(A.sum())
print(A.mean())
print(A.max())
print(A.min())

21
3.5
6
1


In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(A.sum(axis=0))
print(A.sum(axis=1))
print("-"*30)
print(A.mean(axis=0))
print(A.mean(axis=1))

[12 15 18]
[ 6 15 24]
------------------------------
[4. 5. 6.]
[2. 5. 8.]


# Linear algebra basics


Dot product


In [ ]:
vector_1 = np.array([3, -1, 2])
vector_2 = np.array([2, 6, 1])

dot_product = vector_1 @ vector_2
print(dot_product)


# Don't use this method
print(np.dot(vector_1, vector_2))

2
2


In [ ]:
vector_a = np.array([1, 2, 2])

print(np.linalg.norm(vector_a))

3.0


In [ ]:
vector_a = np.array([3, 4, 5])
vector_b = np.array([1, 2, 3])

cosine_similarity = vector_a @ vector_b / \
    (np.linalg.norm(vector_a) * np.linalg.norm(vector_b))
print(cosine_similarity)

0.9827076298239908


Reshaping & Flattening


In [ ]:
arr_1 = np.array([1, 2, 3, 4, 5, 6])
print(arr_1.shape)

arr_2 = arr_1.reshape(2, 3)
print(arr_2)
print(arr_2.shape)


print(arr_1.reshape(2, 4))

(6,)
[[1 2 3]
 [4 5 6]]
(2, 3)
6


ValueError: cannot reshape array of size 6 into shape (2,4)

In [ ]:
arr_1 = np.array([1, 2, 3, 4, 5, 6])
arr_2 = arr_1.reshape(3, -1)
print(arr_2)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
arr_1 = np.array([
    [1, 2, 3],
    [10, 20, 30],
    [100, 200, 300]
])

print(arr_1.flatten())
print(arr_1.reshape(1, -1))

[  1   2   3  10  20  30 100 200 300]
[[  1   2   3  10  20  30 100 200 300]]


Stacking and Concatenating arrays


In [ ]:
a = np.array([1, 5, 7])
b = np.array([4, 3, 10])

c = np.concatenate((a, b), axis=0)
print(c)

[ 1  5  7  4  3 10]


In [ ]:
a = np.array([
    [2, 5, 7, 1],
    [9, 12, 11, 13],
    [7, 6, 18, 12],
])

b = np.array([
    [7, 32, 12, 11],
    [9, 6, 7, 12],
    [5, 10, 6, 9]

])

c = np.concatenate((a, b), axis=0)
print(c)

[[ 2  5  7  1]
 [ 9 12 11 13]
 [ 7  6 18 12]
 [ 7 32 12 11]
 [ 9  6  7 12]
 [ 5 10  6  9]]


In [ ]:
d = np.concatenate((a, b), axis=1)
print(d)

[[ 2  5  7  1  7 32 12 11]
 [ 9 12 11 13  9  6  7 12]
 [ 7  6 18 12  5 10  6  9]]


In [ ]:
a = np.array([1, 5, 7])
b = np.array([4, 3, 10])

c = np.vstack([a, b])
print(c)

print(np.hstack([a, b]))

[[ 1  5  7]
 [ 4  3 10]]
[ 1  5  7  4  3 10]


In [ ]:
a = np.array([
    [1, 5, 7],
    [2, 4, 8]
])

b = np.array([
    [4, 5, 6],
    [3, 7, 8]
])

c = np.hstack([a, b])
print(c)

[[1 5 7 4 5 6]
 [2 4 8 3 7 8]]


Matrix-Vector multiplication


In [ ]:
x = np.array([
    [3, 2, 100],
    [1, 2, 60],
    [4, 3, 20],
    [2, 5, 120]
])

w = np.array([
    [0.3],
    [0.2],
    [0.1]
])

b = 0.8

y = x @ w+b
print(y)

[[12.1]
 [ 7.5]
 [ 4.6]
 [14.4]]


Identity Matrix


In [ ]:
I = np.eye(3, dtype="int64")
print(I)

a = np.array([
    [1, 2, 3],
    [10, 20, 30],
    [100, 200, 300]
])
print("-"*30)
print(a @ I)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
------------------------------
[[  1   2   3]
 [ 10  20  30]
 [100 200 300]]
