In [1]:
import numpy as np

Boolean Masking


In [ ]:
scores = np.array([0.6, 0.9, 0.3, 0.2, 0.75, 0.1])

temp_arr = scores > 0.5

print(temp_arr)

f_arr = scores[temp_arr]
print(f_arr)

print("-"*20)

print(scores[scores > 0.6])

[ True  True False False  True False]
[0.6  0.9  0.75]
--------------------
[0.9  0.75]


arange(x,y,z)

In [4]:
arr = np.arange(0,10,2)
print(arr)

[0 2 4 6 8]


In [5]:
arr = np.arange(0,1,0.1)
print(arr)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [6]:
arr = np.linspace(0,10,5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]
