In [1]:
import numpy as np

Boolean Masking


In [2]:
scores = np.array([0.6, 0.9, 0.3, 0.2, 0.75, 0.1])

temp_arr = scores > 0.5

print(temp_arr)

f_arr = scores[temp_arr]
print(f_arr)

print("-"*20)

print(scores[scores > 0.6])

[ True  True False False  True False]
[0.6  0.9  0.75]
--------------------
[0.9  0.75]


arange(x,y,z)


In [ ]:
arr = np.arange(0, 10, 2)
print(arr)

[0 2 4 6 8]


In [ ]:
arr = np.arange(0, 1, 0.1)
print(arr)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [ ]:
arr = np.linspace(0, 10, 5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [ ]:
arr = np.ones((3, 5))
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
arr = np.zeros((3, 5), dtype="int64")
print(arr)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
# base = np.array([1,2,3,4])
# view = base[0:2]
# view[0]=99
# print(view)
# print(base)

base2 = np.array([1, 2, 3, 4])
safe = base2[0:2].copy()
safe[0] = 99
print(safe)
print(base2)

[99  2]
[1 2 3 4]


Broadcasting


In [12]:
A = np.array([
    [3, 5],
    [8, 9]
])

B = np.array([
    [2, 4],
    [3, 5]
])

print(A+B)
print(B.shape)
print(A.shape)

[[ 5  9]
 [11 14]]
(2, 2)
(2, 2)


In [ ]:
A = np.array([
    [3, 5],
    [8, 9],
    [10, 12]
])

B = np.array([
    [3],
    [2],
    [1]
])

# C = np.array([3,2,1])

print(A+B)
# print(A+C)

[[ 6  8]
 [10 11]
 [11 13]]


In [17]:
arr_2 = np.array([
    [1, 2, 3, 4],
    [2, 3, 4, 5],
    [1, 2, 3, 5],
    [2, 3, 4, 5]
])

arr_3 = np.array([
    [1, 2],
    [2, 3],
    [3, 4],
    [4, 5]
])

print(arr_2.shape)
print(arr_3.shape)

print(arr_2+arr_3)

(4, 4)
(4, 2)


ValueError: operands could not be broadcast together with shapes (4,4) (4,2) 

Aggregations and the axis argument


In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(A.sum())
print(A.mean())
print(A.max())
print(A.min())

21
3.5
6
1


In [23]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(A.sum(axis=0))
print(A.sum(axis=1))

[5 7 9]
[ 6 15]


In [27]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(A.sum(axis=0))
print(A.mean(axis=0))
print("-"*30)
print(A.sum(axis=1))
print(A.mean(axis=1))

[12 15 18]
[4. 5. 6.]
------------------------------
[ 6 15 24]
[2. 5. 8.]
