In [1]:
import numpy as np

Boolean Masking


In [ ]:
scores = np.array([0.6, 0.9, 0.3, 0.2, 0.75, 0.1])

temp_arr = scores > 0.5

print(temp_arr)

f_arr = scores[temp_arr]
print(f_arr)

print("-"*20)

print(scores[scores > 0.6])

[ True  True False False  True False]
[0.6  0.9  0.75]
--------------------
[0.9  0.75]


arange(x,y,z)

In [4]:
arr = np.arange(0,10,2)
print(arr)

[0 2 4 6 8]


In [5]:
arr = np.arange(0,1,0.1)
print(arr)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [6]:
arr = np.linspace(0,10,5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [8]:
arr = np.ones((3,5))
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [10]:
arr = np.zeros((3,5), dtype="int64")
print(arr)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [14]:
# base = np.array([1,2,3,4])
# view = base[0:2]
# view[0]=99
# print(view)
# print(base)

base2 = np.array([1,2,3,4])
safe = base2[0:2].copy()
safe[0]=99
print(safe)
print(base2)

[99  2]
[1 2 3 4]
