In [13]:
import numpy as np

Boolean Masking


In [14]:
scores = np.array([0.6, 0.9, 0.3, 0.2, 0.75, 0.1])

temp_arr = scores > 0.5

print(temp_arr)

f_arr = scores[temp_arr]
print(f_arr)

print("-"*20)

print(scores[scores > 0.6])

[ True  True False False  True False]
[0.6  0.9  0.75]
--------------------
[0.9  0.75]


arange(x,y,z)


In [15]:
arr = np.arange(0, 10, 2)
print(arr)

[0 2 4 6 8]


In [16]:
arr = np.arange(0, 1, 0.1)
print(arr)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [17]:
arr = np.linspace(0, 10, 5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [18]:
arr = np.ones((3, 5))
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [19]:
arr = np.zeros((3, 5), dtype="int64")
print(arr)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [20]:
# base = np.array([1,2,3,4])
# view = base[0:2]
# view[0]=99
# print(view)
# print(base)

base2 = np.array([1, 2, 3, 4])
safe = base2[0:2].copy()
safe[0] = 99
print(safe)
print(base2)

[99  2]
[1 2 3 4]


Broadcasting


In [21]:
A = np.array([
    [3, 5],
    [8, 9]
])

B = np.array([
    [2, 4],
    [3, 5]
])

print(A+B)
print(B.shape)
print(A.shape)

[[ 5  9]
 [11 14]]
(2, 2)
(2, 2)


In [22]:
A = np.array([
    [3, 5],
    [8, 9],
    [10, 12]
])

B = np.array([
    [3],
    [2],
    [1]
])

# C = np.array([3,2,1])

print(A+B)
# print(A+C)

[[ 6  8]
 [10 11]
 [11 13]]


In [23]:
arr_2 = np.array([
    [1, 2, 3, 4],
    [2, 3, 4, 5],
    [1, 2, 3, 5],
    [2, 3, 4, 5]
])

arr_3 = np.array([
    [1, 2],
    [2, 3],
    [3, 4],
    [4, 5]
])

print(arr_2.shape)
print(arr_3.shape)

print(arr_2+arr_3)

(4, 4)
(4, 2)


ValueError: operands could not be broadcast together with shapes (4,4) (4,2) 

Aggregations and the axis argument


In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(A.sum())
print(A.mean())
print(A.max())
print(A.min())

21
3.5
6
1


In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(A.sum(axis=0))
print(A.sum(axis=1))

[5 7 9]
[ 6 15]


In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(A.sum(axis=0))
print(A.mean(axis=0))
print("-"*30)
print(A.sum(axis=1))
print(A.mean(axis=1))

[12 15 18]
[4. 5. 6.]
------------------------------
[ 6 15 24]
[2. 5. 8.]


# Linear algebra basics


Dot Product


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a.dot(b))
print("-"*30)
print(a @ b)

32
------------------------------
32


Find Magnitude


In [ ]:
vector_a = np.array([3, 2, 1])
print(np.linalg.norm(vector_a))

3.7416573867739413


Cosine Similarity


In [ ]:
vector_a = np.array([3, 4, 5])
vector_b = np.array([2, 4, 8])


def cosine_similarity(vector_a, vector_b):
    return (vector_a @ vector_b)/(np.linalg.norm(vector_a)*(np.linalg.norm(vector_b)))


print(cosine_similarity(vector_a, vector_b))

0.95668076976497


The bridge: X @ w + b


In [ ]:
X = np.array([
    [0.8, 0.4, 0.9],
    [0.2, 0.7, 0.6]
])

w = np.array([0.5, -0.2, 0.3])
b = 0.1

scores = X @ w + b
print(scores)

[0.69 0.24]


Reshaping & Flattening


In [ ]:
r = np.arange(6)

print(r.reshape(2, 3))

print("-"*30)

grid = r.reshape(3, 2)
print(grid)

print("-"*30)

print(grid.flatten())

[[0 1 2]
 [3 4 5]]
------------------------------
[[0 1]
 [2 3]
 [4 5]]
------------------------------
[0 1 2 3 4 5]


Stacking & concatenating arrays


In [ ]:
u = np.array([1, 2, 3])
w = np.array([4, 5, 6])

print(np.vstack([u, w]))

print("-"*30)

print(np.hstack([u, w]))

[[1 2 3]
 [4 5 6]]
------------------------------
[1 2 3 4 5 6]


In [ ]:
c1 = np.array([[1], [2]])
c2 = np.array([[3], [4]])

print(np.concatenate([c1, c2], axis=1))

[[1 3]
 [2 4]]


Slicing train/test style splits


In [ ]:
data = np.arange(10)

train = data[:8]
test = data[8:]

print(train)
print(test)

[0 1 2 3 4 5 6 7]
[8 9]


Matrix Vector Multiplication


In [ ]:
X = np.array([
    [0.8, 0.4, 0.9],
    [0.2, 0.7, 0.6]
])

w = np.array([
    [0.5],
    [-0.2],
    [0.3]
]
)
b = 0.1

scores = X @ w + b
print(X.shape)
print(w.shape)

print(scores)
print(scores.shape)

(2, 3)
(3, 1)
[[0.69]
 [0.24]]
(2, 1)


Matrix - Matrix multiplication


In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

C = A @ B
print(C.shape)
print("-"*30)
print(C)

(2, 2)
------------------------------
[[ 58  64]
 [139 154]]


In [ ]:
X = np.array([
    [0.1, 0.2, 0.3],
    [0.4, 0.1, 0.5],
    [0.2, 0.8, 0.1],
    [0.6, 0.3, 0.2]
])

W = np.array([
    [0.5, -0.2],
    [0.1, 0.4],
    [0.3, 0.6]
])

b = np.array([0.05, -0.1])

Y = X @ W + b

print(Y.shape)
print(Y)

(4, 2)
[[0.21 0.14]
 [0.41 0.16]
 [0.26 0.24]
 [0.44 0.02]]


Identity Matrix


In [ ]:
I = np.eye(3, dtype="int64")
print(I)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


Zero matrix and ones matrix


In [ ]:
print(np.zeros((2, 3)))
print("-"*30)
print(np.ones((2, 2)))

[[0. 0. 0.]
 [0. 0. 0.]]
------------------------------
[[1. 1.]
 [1. 1.]]


In [ ]:
# Python lists
list_a = [1, 2, 3]
list_b = [4, 5, 6]

print(list_a + list_b)

# NumPy arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a+b)

[1, 2, 3, 4, 5, 6]
[5 7 9]


In [ ]:
from_list = np.array([1, 2, 3])
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(from_list)
print(matrix)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [27]:
print(np.zeros((2, 3)))
print("-"*30)
print(np.ones((2, 2)))
print("-"*30)
print(np.arange(0, 10, 2))
print("-"*30)
print(np.linspace(0, 1, 5))
print("-"*30)
print(np.eye(3))

[[0. 0. 0.]
 [0. 0. 0.]]
------------------------------
[[1. 1.]
 [1. 1.]]
------------------------------
[0 2 4 6 8]
------------------------------
[0.   0.25 0.5  0.75 1.  ]
------------------------------
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
X = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(X.shape)
print(X.ndim)
print(X.size)
print(X.dtype)

(2, 3)
2
6
int64


In [29]:
print(np.array([1, 2, 3]).dtype)
print(np.array([1.0, 2, 3]).dtype)

prices = np.array([1.5, 2.5, 3.5])
as_int = prices.astype(int)
print(as_int)

int64
float64
[1 2 3]


In [30]:
vector = np.array([1, 2, 3])
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

cube = np.arange(8).reshape(2, 2, 2)

print(vector.ndim)
print(matrix.ndim)
print(cube.ndim)
print(cube.shape)
print(cube)

1
2
3
(2, 2, 2)
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
M = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(M[0, 0])
print(M[1])
print(M[:, 0])
print(M[0:2, 1:3])

10
[40 50 60]
[10 40 70]
[[20 30]
 [50 60]]


In [32]:
scores = np.array([0.2, 0.9, 0.5, 0.95, 0.1])

mask = scores >= 0.5
print(mask)
print(scores[mask])

print(scores[scores >= 0.5])

[False  True  True  True False]
[0.9  0.5  0.95]
[0.9  0.5  0.95]


In [ ]:
arr = np.arange(0, 10, 2)
print(arr)

[0 2 4 6 8]


In [ ]:
arr = np.arange(0, 1, 0.1)
print(arr)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [ ]:
print(np.linspace(0, 10, 5))

[ 0.   2.5  5.   7.5 10. ]


In [40]:
X = np.array([
    [1, 2, 0.7],
    [3, 4, 0.9],
    [5, 6, 0.3]

])

print(X[X[:, 2] > 0.8])

[[3.  4.  0.9]]


In [42]:
base = np.array([1, 2, 3, 4])
view = base[0:2]
view[0] = 99
print(base)
print(view)

print("-"*30)

base2 = np.array([1, 2, 3, 4])
safe = base2[0:2].copy()
safe[0] = 99
print(base2)
print(safe)

[99  2  3  4]
[99  2]
------------------------------
[1 2 3 4]
[99  2]


In [43]:
values = np.array([1, 2, 3, 4])

doubled = []

for v in values:
    doubled.append(v*2)

doubled = values * 2
print(doubled)
print(values + 10)
print(values ** 2)

[2 4 6 8]
[11 12 13 14]
[ 1  4  9 16]


In [44]:
X = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

column_mean = X.mean(axis=0)
print(column_mean)

centered = X - column_mean
print(centered)

[2.5 3.5 4.5]
[[-1.5 -1.5 -1.5]
 [ 1.5  1.5  1.5]]


In [45]:
X = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

row = np.array([10, 20, 30])

print(X + row)

[[11 22 33]
 [14 25 36]]


In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(A.sum())
print(A.mean())
print(A.max())
print(A.min())

21
3.5
6
1


In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(A.sum(axis=0))
print(A.sum(axis=1))

[5 7 9]
[ 6 15]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.dot(a, b))
print(a @ b)

32
32


In [ ]:
P = np.array([
    [1, 2],
    [3, 4]
])

Q = np.array([
    [5, 6],
    [7, 8]
])

print(P @ Q)

[[19 22]
 [43 50]]


In [ ]:
X = np.array([
    [0.8, 0.4, 0.9],
    [0.2, 0.7, 0.6]
])

w = np.array([0.5, -0.2, 0.3])
b = 0.1

scores = X @ w + b
print(scores)

[0.69 0.24]


In [51]:
r = np.arange(6)
print(r.reshape(2, 3))

print(r.reshape(3, 2))

[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]


In [ ]:
print(r.reshape(-1, 2))

grid = r.reshape(2, 3)
print(grid.flatten())

[[0 1]
 [2 3]
 [4 5]]
[0 1 2 3 4 5]


In [ ]:
u = np.array([1, 2, 3])
w = np.array([4, 5, 6])

print(np.vstack([u, w]))

print(np.hstack([u, w]))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [54]:
c1 = np.array([[1], [2]])
c2 = np.array([[3], [4]])

print(np.concatenate([c1, c2], axis=1))

[[1 3]
 [2 4]]
