In [2]:
import numpy as np

In [3]:
list_a = [1, 2, 3]
list_b = [4, 5, 6]

print(list_a + list_b)

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)

[1, 2, 3, 4, 5, 6]
[5 7 9]


In [4]:
from_list = np.array([1, 2, 3])
matrix = np.array([[1, 2, 3], [4, 5, 6]])

print(from_list)
print("-"*30)
print(matrix)

[1 2 3]
------------------------------
[[1 2 3]
 [4 5 6]]


In [5]:
print(np.zeros((2, 3)))
print("-"*30)
print(np.ones((2, 2)))
print("-"*30)
print(np.arange(0, 10, 2))
print("-"*30)
print(np.linspace(0, 1, 5))
print("-"*30)
print(np.eye(3))

[[0. 0. 0.]
 [0. 0. 0.]]
------------------------------
[[1. 1.]
 [1. 1.]]
------------------------------
[0 2 4 6 8]
------------------------------
[0.   0.25 0.5  0.75 1.  ]
------------------------------
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
x = np.array([[1, 2, 3], [4, 5, 6]], dtype="int16")

print(x.shape)
print(x.ndim)
print(x.size)
print(x.dtype)
print(len(x))

(2, 3)
2
6
int16
2


In [7]:
print(np.array([1, 2, 3]).dtype)
print(np.array([1.0, 2, 3]).dtype)

# Convert dtype with astype
prices = np.array([1.5, 2.5, 3.5])
as_int = prices.astype(int)
print(as_int)

int64
float64
[1 2 3]


In [8]:
vector = np.array([1, 2, 3])
matrx = np.array([[1, 2, 3], [4, 5, 6]])
cube = np.arange(8).reshape(2, 2, 2)

print(vector.ndim)
print(matrix.ndim)
print(cube.ndim)
print(cube.shape)
print(cube)

1
2
3
(2, 2, 2)
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
M = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(M[0, 0])  # 10
print("-"*30)
print(M[1])    # [40, 50, 60]
print("-"*30)
print(M[:, 0])  # 10,40,70
print("-"*30)
print(M[0:2, 1:3])  # [[20,30],[50,60]]

10
------------------------------
[40 50 60]
------------------------------
[10 40 70]
------------------------------
[[20 30]
 [50 60]]


In [ ]:
scores = np.array([0.2, 0.9, 0.5, 0.95, 0.1])

mask = scores >= 0.5
print(mask)

print(scores[mask])
print("-"*30)

print(scores[scores >= 0.5])

[False  True  True  True False]
[0.9  0.5  0.95]
------------------------------
[0.9  0.5  0.95]


In [ ]:
X = np.array([
    [1, 2, 0.7],
    [3, 4, 0.9],
    [5, 6, 0.3]
])

print(X[X[:, 2] >= 0.8])

[[3.  4.  0.9]]


In [14]:
base = np.array([1, 2, 3, 4])
view = base[0:2]
view[0] = 99
print(base)

base2 = np.array([1, 2, 3, 4])
safe = base2[0:2].copy()
safe[0] = 99
print(base2)

[99  2  3  4]
[1 2 3 4]


In [15]:
values = np.array([1, 2, 3, 4])

doubled = []
for v in values:
    doubled.append(v * 2)

doubled = values * 2
print(doubled)
print(values + 10)
print(values ** 2)

[2 4 6 8]
[11 12 13 14]
[ 1  4  9 16]
