In [2]:
import numpy as np

In [3]:
list_a = [1,2,3]
list_b = [4,5,6]

print(list_a + list_b)

a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)

[1, 2, 3, 4, 5, 6]
[5 7 9]


In [4]:
from_list = np.array([1,2,3])
matrix = np.array([[1,2,3],[4,5,6]])

print(from_list)
print("-"*30)
print(matrix)

[1 2 3]
------------------------------
[[1 2 3]
 [4 5 6]]


In [7]:
print(np.zeros((2,3)))
print("-"*30)
print(np.ones((2,2)))
print("-"*30)
print(np.arange(0,10,2))
print("-"*30)
print(np.linspace(0,1,5))
print("-"*30)
print(np.eye(3))

[[0. 0. 0.]
 [0. 0. 0.]]
------------------------------
[[1. 1.]
 [1. 1.]]
------------------------------
[0 2 4 6 8]
------------------------------
[0.   0.25 0.5  0.75 1.  ]
------------------------------
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
x = np.array([[1,2,3],[4,5,6]],dtype="int16")

print(x.shape)
print(x.ndim)
print(x.size)
print(x.dtype)
print(len(x))


(2, 3)
2
6
int16
2


In [14]:
print(np.array([1,2,3]).dtype)
print(np.array([1.0,2,3]).dtype)

# Convert dtype with astype
prices = np.array([1.5,2.5,3.5])
as_int = prices.astype(int)
print(as_int)

int64
float64
[1 2 3]
